# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.NOTE_TOKEN }}
  
    - name: set env
      run: echo "::set-env name=message::$(git --no-pager log  --pretty=%an -1)"
    
    - name: check status
      if: ! contains(${{ env.message }}, "github action")

    # Runs a single command using the runners shell
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    
    - name: build
      run: |
        npm install gitbook-cli -g
        gitbook build

    # Runs a set of commands using the runners shell
    - name: commit
      run: |
        git config --global user.name 'github action'
        git config --global user.email 'action@github.com'
        ls | grep docs |xargs rm -rf
        mv _book  docs
        ls | grep _book |xargs rm -rf
        git add docs
        git commit -m "gitbook build"
        git push --force --set-upstream origin master
          
